services:
  - type: web
    name: billing-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://billing-system-backend-x91f.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
