import { useEffect, useMemo, useState } from "react";
import { Search, Plus, Trash2, ReceiptText, LoaderCircle, CheckCircle2, ShoppingBag } from "lucide-react";
import API from "../../services/axios";
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"});

export default function InvoiceCreate(){
 const [products,setProducts]=useState([]),[search,setSearch]=useState(""),[selected,setSelected]=useState(null),[qty,setQty]=useState(1),[items,setItems]=useState([]),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{API.get("/product/all").then(r=>setProducts(r.data)).catch(()=>setNotice("Unable to load products"));},[]);
 const suggestions=useMemo(()=>search.trim()?products.filter(p=>p.pname.toLowerCase().includes(search.toLowerCase())).slice(0,6):[],[search,products]);
 const add=()=>{if(!selected)return setNotice("Choose a product from the search results");const amount=Math.max(1,Number(qty));if(amount>selected.stock)return setNotice(`Only ${selected.stock} units available`);setItems(old=>{const found=old.find(i=>i.productId===selected._id);if(found){const next=found.quantity+amount;if(next>selected.stock){setNotice(`Only ${selected.stock} units available`);return old;}return old.map(i=>i.productId===selected._id?{...i,quantity:next,total:i.price*next}:i);}return [...old,{productId:selected._id,pname:selected.pname,pcat:selected.category,price:selected.price,quantity:amount,total:selected.price*amount}];});setSearch("");setSelected(null);setQty(1);setNotice("");};
 const subtotal=items.reduce((s,i)=>s+i.total,0),tax=subtotal*.05,total=subtotal+tax;
 const create=async()=>{if(!items.length)return setNotice("Add at least one item to continue");setSaving(true);try{await API.post("/bill/create",{invoiceNo:`INV-${Date.now()}`,date:new Date(),items,totalAmount:total});setItems([]);setNotice("Invoice created successfully");const {data}=await API.get("/product/all");setProducts(data);}catch(e){setNotice(e.response?.data?.message||"Unable to create invoice");}finally{setSaving(false);}};
 return <div className="page-shell"><div><h1 className="page-heading">Create invoice</h1><p className="page-copy">Search products, add quantities and complete a new sale.</p></div>{notice&&<div className={`rounded-xl border px-4 py-3 text-sm ${notice.includes("successfully")?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-amber-200 bg-amber-50 text-amber-800"}`}>{notice}</div>}
 <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-6"><section className="panel p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><ShoppingBag size={20}/></span><div><h2 className="font-bold">Add items</h2><p className="text-xs text-slate-500">Select a product and quantity</p></div></div><div className="grid gap-3 sm:grid-cols-[1fr_100px_auto]"><div className="relative"><Search className="absolute left-3 top-3.5 text-slate-400" size={17}/><input className="field pl-10" placeholder="Search by product name" value={search} onChange={e=>{setSearch(e.target.value);setSelected(null)}}/>{suggestions.length>0&&<div className="absolute z-20 mt-2 w-full overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl">{suggestions.map(p=><button type="button" key={p._id} className="flex w-full items-center justify-between px-4 py-3 text-left text-sm hover:bg-slate-50" onClick={()=>{setSelected(p);setSearch(p.pname)}}><span><b>{p.pname}</b><small className="ml-2 text-slate-400">{p.stock} in stock</small></span><b className="text-brand-700">{money.format(p.price)}</b></button>)}</div>}</div><input className="field" type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><button onClick={add} className="primary-btn"><Plus size={18}/>Add</button></div></section>
 <section className="panel overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="font-bold">Invoice items</h2><p className="text-xs text-slate-500">{items.length} unique items added</p></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>Price</th><th>Qty</th><th>Total</th><th/></tr></thead><tbody>{items.length===0?<tr><td colSpan="5"><div className="py-12 text-center"><ReceiptText className="mx-auto mb-3 text-slate-300" size={34}/><p className="font-medium text-slate-500">Your invoice is empty</p><p className="text-xs text-slate-400">Search and add products above</p></div></td></tr>:items.map(i=><tr key={i.productId}><td className="font-semibold text-slate-900">{i.pname}<small className="block font-normal text-slate-400">{i.pcat}</small></td><td>{money.format(i.price)}</td><td>{i.quantity}</td><td className="font-semibold">{money.format(i.total)}</td><td><button onClick={()=>setItems(items.filter(x=>x.productId!==i.productId))} className="text-slate-400 hover:text-red-600"><Trash2 size={17}/></button></td></tr>)}</tbody></table></div></section></div>
 <aside className="panel h-fit p-6 xl:sticky xl:top-28"><div className="mb-6 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-slate-900 text-white"><ReceiptText size={21}/></span><div><h2 className="font-bold">Bill summary</h2><p className="text-xs text-slate-500">{new Date().toLocaleDateString("en-IN",{dateStyle:"medium"})}</p></div></div><div className="space-y-3 border-y border-dashed border-slate-200 py-5 text-sm"><p className="flex justify-between text-slate-500"><span>Subtotal</span><b className="text-slate-800">{money.format(subtotal)}</b></p><p className="flex justify-between text-slate-500"><span>GST (5%)</span><b className="text-slate-800">{money.format(tax)}</b></p></div><div className="flex justify-between py-6"><span className="font-semibold">Amount due</span><b className="text-2xl text-slate-950">{money.format(total)}</b></div><button disabled={saving||!items.length} onClick={create} className="primary-btn w-full">{saving?<LoaderCircle className="animate-spin" size={18}/>:<CheckCircle2 size={18}/>}Complete sale</button><p className="mt-3 text-center text-[11px] text-slate-400">Stock is updated automatically after billing</p></aside></div></div>;
}
